### ISSUE TITLE
Yarn command fails while execution of cake build command

### ISSUE THREAD

**Issue by shardulbanker** [cqframework/cql-execution#130]
I want to use this cql-execution application for eCQM 2020 measures. Based on the guideline, I have configured application in my Windows 10-64 bit PC.  I am facing below error during "yarn install" command.
---------------------------------------------------------------------------------------
D:\git_workspace\cql-execution-coffee>yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ ./node_modules/.bin/cake build && ./node_modules/.bin/cake build-cql4browsers
events.js:282
      throw er; // Unhandled 'error' event
      ^

Error: spawn coffee ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn coffee',
  path: 'coffee',
  spawnargs: [ '-c', '-m', '-o', 'lib', 'src' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
----------------------------------------------------------------------------------------------------
I have installed and added "coffee" as part of system environment variables and added as part of path so that it is available from any location.

Below is the required versions installed.
--------------------------------------------------------------------------------
D:\git_workspace\cql-execution-coffee>coffee -v
CoffeeScript version 1.12.7

D:\git_workspace\cql-execution-coffee>yarn -v
1.22.4

D:\git_workspace\cql-execution-coffee>npm -v
6.13.4

D:\git_workspace\cql-execution-coffee>node -v
v13.5.0
-----------------------------------------------------------------------------------

I am stuck and not able to proceed further. I don't have knowledge on coffee script. Based on some of google references, I found that "spawn" gives the error and change to "exec" Is there any way I can change from spawn to exec?

Any kind of help is really appreciated. Thanks.

**Comment by shardulbanker** [comment]
I have resolved the issue on my own. I got the reference from one of the link.
https://stackoverflow.com/questions/19268817/coffeescript-and-cake-error

Based on this, I updated Cakefile by changing "coffee.cmd" instead of "coffee" and now I am able to run "yarn install" and as well as "cake build" command.

Thanks.
